# -*- coding: utf-8 -*-
"""Pinger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1juob3SfA2_cnCLDPMYpqZz-pfKTWaxNr

**패키지 설치**
"""

# Python
!pip install python-dotenv
# 서버 관련
!pip install flask flask-cors pyngrok
!pip install flask-ngrok
!pip install pyngrok
# AI 관련
!pip install ftfy regex tqdm
!pip install controlnet_aux
!pip install diffusers transformers accelerate
# Firebase
!pip install flask flask-ngrok firebase-admin

"""**초기 환경 설정**

 - Google Drive 마운트

 - 환경 변수 로드
"""

from google.colab import drive
from dotenv import load_dotenv

drive.mount('/content/drive')
load_dotenv('/content/drive/MyDrive/Colab Notebooks/Pinger/.env')



"""**이미지 생성 AI**"""

import base64
import io
from PIL import Image
import torch
from datetime import datetime

from diffusers import ControlNetModel, StableDiffusionControlNetPipeline, UniPCMultistepScheduler
from controlnet_aux import HEDdetector

class ImageAI:
    def __init__(self):
        self.hed = HEDdetector.from_pretrained('lllyasviel/Annotators')

        # ControlNet Scribble 모델 로드
        self.controlnet = ControlNetModel.from_pretrained(
            "lllyasviel/sd-controlnet-scribble",
            torch_dtype=torch.float16
        )

        # Stable Diffusion 파이프라인 설정
        self.pipe = StableDiffusionControlNetPipeline.from_pretrained(
            "runwayml/stable-diffusion-v1-5",
            controlnet=self.controlnet,
            safety_checker=None,
            torch_dtype=torch.float16
        )

        self.pipe.scheduler = UniPCMultistepScheduler.from_config(self.pipe.scheduler.config)
        self.pipe.enable_model_cpu_offload()
    ## __init__(self)

    def generate_from_sketch(self, b64_string: str, prompt: str) -> str:
        init_image = self.__base64_to_pil(b64_string)

        detected_scribble = self.hed(init_image) # 선 감지

        output_image = self.pipe(
            prompt=prompt,
            image=detected_scribble,
            guidance_scale=7.5,
            num_inference_steps=30
        ).images[0]

        self.__save_to_drive(output_image, prompt)

        return self.__pil_to_base64(output_image)
    ## generate_from_sketch(self, b64_string: str, prompt: str)

    @staticmethod
    def __save_to_drive(img: Image.Image, prompt: str):
        save_dir = "/content/drive/MyDrive/"
        os.makedirs(save_dir, exist_ok=True)

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{timestamp}.png"
        save_path = os.path.join(save_dir, filename)
        img.save(save_path)
        print(f"이미지가 Google Drive에 저장되었습니다: {save_path}")
    ## __save_to_drive(img: Image.Image, prompt: str)

    @staticmethod
    def __base64_to_pil(b64_string: str) -> Image.Image:
        img_bytes = base64.b64decode(b64_string)
        img = Image.open(io.BytesIO(img_bytes)).convert("RGB")
        return img
    ## __base64_to_pil(b64_string: str)

    @staticmethod
    def __pil_to_base64(img: Image.Image) -> str:
        buffered = io.BytesIO()
        img.save(buffered, format="PNG")
        return base64.b64encode(buffered.getvalue()).decode()
    ## __pil_to_base64(img: Image.Image)
## class ImageAI

"""**REST** **API**

- `generate` : 이미지 생성

- `create` : DB에 저장
"""

import os
from pyngrok import ngrok
from flask import Flask, render_template, request, jsonify, send_from_directory
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)
ngrok.set_auth_token(os.getenv('NGROK_AUTH_TOKEN'))

image_ai = ImageAI()

@app.route("/generate", methods=["POST"])
def generate():
    data = request.json
    base64_image = data.get("image")
    prompt = data.get("prompt")

    if not base64_image or not prompt:
        return jsonify({"error": "Missing image or prompt"}), 400

    try:
        result_base64 = image_ai.generate_from_sketch(base64_image, prompt)
        return jsonify({"image": result_base64})
    except Exception as e:
        return jsonify({"error": str(e)}), 500
## generate

if __name__ == '__main__':
    public_url = ngrok.connect(5000)
    print(" * ngrok tunnel: ", public_url)
    app.run()